-- Create the orders table
CREATE TABLE IF NOT EXISTS orders (
    id TEXT PRIMARY KEY,
    customer_name TEXT NOT NULL,
    customer_phone TEXT NOT NULL,
    customer_address TEXT NOT NULL,
    delivery_location TEXT NOT NULL,
    payment_method TEXT NOT NULL,
    items JSONB NOT NULL,
    subtotal NUMERIC NOT NULL,
    shipping_fee NUMERIC NOT NULL,
    total NUMERIC NOT NULL,
    status TEXT DEFAULT 'Pending',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable Row Level Security (RLS) or add policies for anonymous read/write
ALTER TABLE orders ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon insert on orders" ON orders 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon select on orders" ON orders 
    FOR SELECT USING (true);

-- Create the reviews table
CREATE TABLE IF NOT EXISTS reviews (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    product_id TEXT NOT NULL,
    stars TEXT NOT NULL,
    rating_val NUMERIC,
    text_en TEXT NOT NULL,
    text_bn TEXT NOT NULL,
    author TEXT NOT NULL,
    verified BOOLEAN DEFAULT false,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS and add policies for reviews
ALTER TABLE reviews ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon insert on reviews" ON reviews 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon select on reviews" ON reviews 
    FOR SELECT USING (true);

-- Create the users table
CREATE TABLE IF NOT EXISTS users (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name TEXT NOT NULL,
    email_or_phone TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Enable RLS and add policies for users
ALTER TABLE users ENABLE ROW LEVEL SECURITY;

CREATE POLICY "Allow anon insert on users" ON users 
    FOR INSERT WITH CHECK (true);

CREATE POLICY "Allow anon select on users" ON users 
    FOR SELECT USING (true);

